version: '3.5'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1L0UpRWZuNXs
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql

volumes:
  mysql:
    name: mysql
    external: true

networks:
  mysql:
    name: mysql
    external: true
