version: '3.5'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=OKdxGRE2BFR7
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  postgres:
    name: postgres
    external: true

networks:
  postgres:
    name: postgres
    external: true
