version: '3.7'

services:
  docker_registry:
    image: registry:2
    container_name: docker_registry
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry
    networks:
      - public_proxy

volumes:
  registry:
    name: registry
    external: true

networks:
  public_proxy:
    name: public_proxy
    external: true
