version: '3.7'

services:
  docker_registry:
    image: registry:2
    container_name: docker_registry
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry
    networks:
      - docker_registry
      - public_proxy

  docker_registry_ui:
    image: jc21/registry-ui
    container_name: docker_registry_ui
    ports:
      - 8020:80
    environment:
      - REGISTRY_HOST=docker.osl.teoworks.com
      - REGISTRY_DOMAIN=docker.osl.teoworks.com
    networks:
      - docker_registry

volumes:
  registry:
    name: registry
    external: true

networks:
  docker_registry:
    name: docker_registry
  public_proxy:
    name: public_proxy
    external: true
