version: '3.7'

services:
  docker_registry:
    image: registry:2
    container_name: docker_registry
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - docker:/var/lib/registry
    networks:
      - docker

  docker_registry_ui:
    image: jc21/registry-ui
    container_name: docker_registry_ui
    restart: unless-stopped
    depends_on:
      - docker_registry
    ports:
      - 8020:80
    environment:
      - REGISTRY_HOST=docker.osl.teoworks.com
      - REGISTRY_DOMAIN=docker.osl.teoworks.com
    networks:
      - docker

volumes:
  docker:
    name: docker
    external: true

networks:
  docker:
    name: docker
    external: true
