version: '3.7'

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - nexus:/nexus-data
    networks:
      - nexus

volumes:
  nexus:
    name: nexus
    external: true

networks:
  nexus:
    name: nexus
    external: true
