version: '3.5'

services:
  kafka:
    image: acntechie/kafka
    container_name: kafka
    restart: unless-stopped
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka.osl.teoworks.com:9092
      - ZOOKEEPER_HOSTS=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - kafka

  zookeeper:
    image: acntechie/zookeeper
    container_name: zookeeper
    restart: unless-stopped
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_HOSTS=zookeeper:2888:3888
    networks:
      - kafka

networks:
  kafka:
    name: kafka
    external: true
