ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE TABLESPACE DUMMY
  DATAFILE 'DUMMY.dat'
  SIZE 10M
  AUTOEXTEND ON;

CREATE USER DUMMY
  IDENTIFIED BY dummy
  DEFAULT TABLESPACE DUMMY
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON DUMMY;

GRANT CONNECT, RESOURCE, CREATE SESSION TO DUMMY;
