version: '3.7'

services:
  devproxy:
    image: haproxy
    container_name: haproxy
    ports:
      - 80:80
      - 443:443
      - 1936:1936
    volumes:
      - ./resources/etc/haproxy:/usr/local/etc/haproxy:ro
      - /dev/log:/dev/log
