version: '3.7'

services:
  public_proxy:
    image: ubuntu
    container_name: admin_ubuntu
    extra_hosts:
      - "ci.osl.internal:10.1.0.5"
    networks:
      - public_proxy
    command: tail -f /var/log/faillog

networks:
  public_proxy:
    name: public_proxy
    external: true
