version: '3.5'

services:
  ldap:
    image: osixia/openldap
    container_name: ldap
    hostname: ldap.osl.teoworks.com
    restart: unless-stopped
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_ORGANISATION=teoworks
      - LDAP_DOMAIN=osl.teoworks.com
      - LDAP_BASE_DN=
      - LDAP_ADMIN_PASSWORD=V4R3rMhuLcLI
      - LDAP_CONFIG_PASSWORD=e6GD562Ni08G
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly
      - LDAP_READONLY_USER_PASSWORD=7j8X9N9EGyFY
    volumes:
      - ldap:/var/lib/ldap
    networks:
      - ldap

volumes:
  ldap:
    name: ldap
    external: true

networks:
  ldap:
    name: ldap
    external: true
