version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - 8010:8080
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./resources/entrypoint.sh:/entrypoint.sh
    networks:
      - public_proxy
    user: root
    entrypoint: /entrypoint.sh

volumes:
  jenkins:
    name: jenkins
    external: true

networks:
  public_proxy:
    name: public_proxy
    external: true
