version: '3.7'

services:
  jenkins:
    image: teoware/jenkins
    container_name: jenkins
    ports:
      - 8010:8080
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public_proxy

volumes:
  jenkins:
    name: jenkins
    external: true

networks:
  public_proxy:
    name: public_proxy
    external: true
