version: '3.7'

services:
  jenkins:
    image: teoware/jenkins
    container_name: jenkins
    restart: unless-stopped
    ports:
      - 8010:8080
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
      - nexus

volumes:
  jenkins:
    name: jenkins
    external: true

networks:
  jenkins:
    name: jenkins
    external: true
  nexus:
    name: nexus
    external: true
