version: '3.5'

services:
  uaa:
    image: acntechie/uaa
    container_name: uaa
    restart: unless-stopped
    ports:
      - 8060:8080
    environment:
      - SPRING_PROFILES_ACTIVE=postgresql,default
    volumes:
      - ./resources/uaa.yml:/usr/local/uaa/uaa.yml
    networks:
      - uaa
      - postgres

networks:
  uaa:
    name: uaa
    external: true
  postgres:
    name: postgres
    external: true
