version: '3.7'

services:
  haproxy:
    image: haproxy
    container_name: haproxy
    restart: unless-stopped
    ports:
      - 80:80
      - 1936:1936
    extra_hosts:
      - "osl.teoworks.internal:10.1.0.5"
    volumes:
      - ./resources/etc/haproxy:/usr/local/etc/haproxy:ro
    networks:
      - haproxy

networks:
  haproxy:
    name: haproxy
    external: true
